/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/efforts/{number}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Read Effort
         * @description Read an effort's ticket graph from GitHub afresh (ADR-0003).
         */
        post: operations["read_effort_api_efforts__number__read_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_api_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gate/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Read Gate
         * @description Run the start gate's six checks afresh. Looking raises nothing for a person.
         */
        post: operations["read_gate_api_gate_read_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/image/build": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Build Image
         * @description Build the session image. Builds happen only here, when a person clicks.
         */
        post: operations["build_image_api_image_build_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/image/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Read Image
         * @description Read what the session image would be now (ADR-0005).
         */
        post: operations["read_image_api_image_read_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Beat
         * @description One meaningful moment in a session, derived from its events and never stored.
         *
         *     Folding the session's events again gives the same beats with the same ids, so a
         *     replay tells exactly the story that was watched live.
         */
        Beat: {
            /**
             * At
             * Format: date-time
             * @description When its first event arrived.
             */
            at: string;
            beat: components["schemas"]["BeatKind"];
            /**
             * Chapter
             * @description 0 for Orient, before the first red; then cycle 1, 2, ….
             */
            chapter: number;
            /**
             * Id
             * @description `beat:<session>:<seq>`, where `seq` is its first event's.
             */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "beat";
            /**
             * Output
             * @description What a red run printed; null for every other beat.
             */
            output: string | null;
            /** @description The test run a red, green or refactor rests on. */
            run: components["schemas"]["TestRun"] | null;
            /**
             * Seq
             * @description Its first event's place in the session; beats sort by it.
             */
            seq: number;
            /**
             * Session
             * @description The session's run id.
             */
            session: string;
            /**
             * Text
             * @description One sentence.
             */
            text: string;
        };
        /**
         * BeatKind
         * @description What kind of moment a beat is.
         * @enum {string}
         */
        BeatKind: "read" | "remark" | "red" | "green" | "refactor" | "outcome" | "working";
        /**
         * BuildFinished
         * @description How the last build ended.
         */
        BuildFinished: {
            /**
             * Checks
             * @description The probe's checks; empty when it never built.
             */
            checks: components["schemas"]["ProbeCheck"][];
            /**
             * Error
             * @description Why the build itself failed; null when it built.
             */
            error: string | null;
            /**
             * Id
             * @constant
             */
            id: "build_finished";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "build_finished";
            /**
             * Ready
             * @description Built and passed its probe, so sessions may use it.
             */
            ready: boolean;
            /** Tag */
            tag: string;
        };
        /**
         * BuildOutput
         * @description One line of the last build's output, as Docker printed it.
         */
        BuildOutput: {
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "build_output";
            /** Line */
            line: string;
            /**
             * Number
             * @description Where the line falls in the output, counting from 0.
             */
            number: number;
        };
        /**
         * Checks
         * @description A pull request's checks, rolled up. A PR with no checks has none of these.
         * @enum {string}
         */
        Checks: "passing" | "pending" | "failing";
        /**
         * ChronicleLine
         * @description One line of the chronicle: one thing that moved a ticket, with what it directly
         *     caused. Derived from GitHub's timelines and the session rows, never stored, so a
         *     rebuild gives the same lines with the same ids.
         */
        ChronicleLine: {
            /**
             * At
             * Format: date-time
             * @description When its cause happened on GitHub; lines sort by it.
             */
            at: string;
            /** Effort */
            effort: number;
            /**
             * Effort Title
             * @description Shown on the right of the line, in place of a skill.
             */
            effort_title: string;
            /**
             * Id
             * @description `chronicle:<effort>:<ticket>:<movement>:<when>`, of its cause.
             */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "chronicle_line";
            /** @description What its cause was, which picks its glyph. */
            movement: components["schemas"]["Movement"];
            /**
             * Parts
             * @description Its one or two sentences, in order.
             */
            parts: components["schemas"]["LinePart"][];
        };
        /**
         * Effort
         * @description An effort's whole ticket graph: its spec issue, and every ticket under it.
         */
        Effort: {
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "effort";
            /** Number */
            number: number;
            /**
             * Tickets
             * @description The ids of its tickets, each an item of its own.
             */
            tickets: string[];
            /** Title */
            title: string;
            /**
             * Trunk
             * @description The repo's default branch, which the effort meets once, when it ships.
             */
            trunk: string;
        };
        /**
         * EffortUnreadable
         * @description An effort Wayfarer was asked to read and could not. It stands in the effort's place.
         */
        EffortUnreadable: {
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "effort_unreadable";
            /** Number */
            number: number;
            /**
             * Reason
             * @description Why, in words for the person.
             */
            reason: string;
        };
        /**
         * EnvironmentFailure
         * @description The one Needs you item a failed start gate raises, however many starts it refused.
         */
        EnvironmentFailure: {
            /** Failed */
            failed: components["schemas"]["GateCheck"][];
            /**
             * Id
             * @description Stays the same while the gate keeps failing, so it is one item.
             */
            id: string;
            /**
             * Kind
             * @constant
             */
            kind: "environment";
            /**
             * Reason
             * @description Which checks failed and why, in plain words.
             */
            reason: string;
        };
        /**
         * GateCheck
         * @description One of the start gate's six checks, and what it found.
         */
        GateCheck: {
            /**
             * Detail
             * @description What was found, in plain words, saying how to fix it when it failed. Names a credential's variable, never its value.
             */
            detail: string;
            /**
             * Name
             * @description What must hold, in plain words.
             */
            name: string;
            /** Passed */
            passed: boolean;
        };
        /**
         * GateStatus
         * @description The start gate as it stands now: all six checks, run afresh.
         */
        GateStatus: {
            /** Checks */
            checks: components["schemas"]["GateCheck"][];
            /**
             * Id
             * @constant
             */
            id: "gate";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "gate";
            /**
             * Passed
             * @description Every check passed, so a session may start.
             */
            passed: boolean;
            /** @description The item the gate raised when it last refused a start; null when it has not refused one, or has admitted one since. */
            raised: components["schemas"]["EnvironmentFailure"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Health
         * @description That the process is up, and which Wayfarer it is.
         */
        Health: {
            /** Version */
            version: string;
        };
        /**
         * ImageStatus
         * @description The image this repo's sessions run in: Wayfarer's base plus the repo's layer (ADR-0005).
         */
        ImageStatus: {
            /** Building */
            building: boolean;
            /**
             * Id
             * @constant
             */
            id: "image";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "image";
            /**
             * Layer
             * @description Where the repo's layer lives, relative to the clone.
             */
            layer: string;
            /**
             * Ready
             * @description That tag exists, so it was built and passed its probe.
             */
            ready: boolean;
            /**
             * Refusal
             * @description Why no image can be built for this repo, in words for the person; null when one can.
             */
            refusal: string | null;
            /**
             * Tag
             * @description The tag an image of the current inputs has; null when refused.
             */
            tag: string | null;
        };
        /**
         * LinePart
         * @description A run of a chronicle line's words. A ticket's part is its title, and links to it.
         */
        LinePart: {
            /** Text */
            text: string;
            /**
             * Ticket
             * @description The ticket this part names; null for plain words.
             */
            ticket: number | null;
        };
        /**
         * Movement
         * @description What moved a ticket, and so what a chronicle line tells. Never a stage.
         * @enum {string}
         */
        Movement: "taken" | "asked" | "answered" | "held" | "let_land" | "retried" | "landed" | "closed";
        /**
         * ProbeCheck
         * @description One thing the probe proved, or failed to prove, about a newly built image.
         */
        ProbeCheck: {
            /** Detail */
            detail: string;
            /** Name */
            name: string;
            /** Passed */
            passed: boolean;
        };
        /**
         * PullRequest
         * @description The pull request carrying a ticket's work, from the ticket's own branch.
         */
        PullRequest: {
            /** Approved */
            approved: boolean;
            /** Base */
            base: string;
            /** Branch */
            branch: string;
            checks: components["schemas"]["Checks"] | null;
            /** Draft */
            draft: boolean;
            /** Head Commit */
            head_commit: string;
            /** Merge Commit */
            merge_commit: string | null;
            /** Merged */
            merged: boolean;
            /** Number */
            number: number;
        };
        /**
         * Removal
         * @description The item with this id is gone.
         */
        Removal: {
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "removal";
        };
        /**
         * Snapshot
         * @description Everything there is, replacing whatever the browser held.
         */
        Snapshot: {
            /** Items */
            items: (components["schemas"]["ImageStatus"] | components["schemas"]["BuildOutput"] | components["schemas"]["BuildFinished"] | components["schemas"]["Effort"] | components["schemas"]["EffortUnreadable"] | components["schemas"]["Ticket"] | components["schemas"]["GateStatus"] | components["schemas"]["Beat"] | components["schemas"]["ChronicleLine"])[];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "snapshot";
        };
        /**
         * TestRun
         * @description One test run, as `wf-test` reported it on its own line.
         */
        TestRun: {
            /**
             * Exit
             * @description The tests' real exit status: 0 is green, anything else red.
             */
            exit: number;
            /**
             * Failed
             * @description Null when the runner wrote no JUnit report.
             */
            failed: number | null;
            /**
             * Failing
             * @description The failing tests' names, when the runner wrote them.
             */
            failing: string[];
            /**
             * Passed
             * @description Null when the runner wrote no JUnit report.
             */
            passed: number | null;
        };
        /**
         * Ticket
         * @description One ticket in an effort, as GitHub has it now.
         */
        Ticket: {
            /** Assignees */
            assignees: string[];
            /** Blocked By */
            blocked_by: number[];
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "ticket";
            /** Labels */
            labels: string[];
            /** Number */
            number: number;
            /** Open */
            open: boolean;
            /** Open Blockers */
            open_blockers: number;
            pull_request: components["schemas"]["PullRequest"] | null;
            state: components["schemas"]["TicketState"];
            /** Title */
            title: string;
        };
        /**
         * TicketState
         * @description Where a ticket stands, derived from GitHub on every read and never stored.
         *
         *     When a ticket matches more than one, it takes the first in this order.
         * @enum {string}
         */
        TicketState: "landed" | "closed" | "asked" | "held" | "landing" | "in_review" | "building" | "takeable" | "blocked";
        /**
         * Upsert
         * @description One item, new or replacing the one with its id.
         */
        Upsert: {
            /** Item */
            item: components["schemas"]["ImageStatus"] | components["schemas"]["BuildOutput"] | components["schemas"]["BuildFinished"] | components["schemas"]["Effort"] | components["schemas"]["EffortUnreadable"] | components["schemas"]["Ticket"] | components["schemas"]["GateStatus"] | components["schemas"]["Beat"] | components["schemas"]["ChronicleLine"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "upsert";
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_effort_api_efforts__number__read_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_api_events_get: {
        parameters: {
            query?: never;
            header?: {
                "last-event-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_gate_api_gate_read_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    build_image_api_image_build_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    read_image_api_image_read_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
